name: BB Bot - Newsletter Diario

on:
  schedule:
    - cron: '30 13 * * *'  # 13:30 UTC = 9:30 Chile
  workflow_dispatch:

jobs:
  run-bbbot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Recuperar historial anterior
        uses: actions/download-artifact@v4
        with:
          name: state
          path: .
        continue-on-error: true

      - name: Verificar día de la semana
        run: |
          echo "Día de la semana: $(date +%A)"
          echo "Hora local: $(date)"

      - name: Ejecutar BB Bot
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          python bbbot.py
          cat bbbot.log

      - name: Guardar historial actualizado
        uses: actions/upload-artifact@v4
        with:
          name: state
          path: |
            state.json
            perplexity_response.json
          retention-days: 7
