name: BB Bot - Newsletter Diario

on:
  schedule:
    - cron: '30 13 * * 1-5' # Lunes a Viernes a las 13:30 UTC (9:30 Chile)
  workflow_dispatch:

jobs:
  run-bbbot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Recuperar historial
        uses: actions/download-artifact@v4
        with:
          name: history
          path: .
        continue-on-error: true

      - name: Crear credentials.json desde el secreto
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: echo "$GOOGLE_CREDENTIALS" > credentials.json

      - name: Depurar variables de entorno
        env:
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          echo "Longitud de SMTP_PASS: ${#SMTP_PASS}"
          echo "Las credenciales de SMTP se usarán en el siguiente paso."

      - name: Ejecutar BB Bot
        id: run_bot
        continue-on-error: true
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          python bbbot.py

      - name: Guardar historial actualizado
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: history
          path: |
            weekly_products.json
            product_history.json
          retention-days: 90
